/* Auto-generated by scripts/sync-blog.mjs — do not edit */
import type { BlogPost } from "./blog-types";

export const ALL_BLOG_POSTS: BlogPost[] = [
  {
    "title": "Draft pipeline test",
    "slug": "draft-pipeline-test",
    "description": "Internal placeholder to verify blog build, RSS, and llms exclusions.",
    "date": "Tue Oct 06 2026 00:00:00 GMT+0000 (Coordinated Universal Time)",
    "keywords": [
      "test",
      "draft"
    ],
    "faq": [
      {
        "q": "Is this post public?",
        "a": "No. It is draft-only and omitted from listings, sitemap, and llms.txt."
      }
    ],
    "draft": true,
    "body": "## Hidden section\n\nThis post exists so the markdown sync pipeline can be tested without publishing content.\n\n[Success chime](/entries/ui-success-chime)"
  }
] as BlogPost[];
