/* Auto-generated by scripts/sync-entries.mjs — do not edit */
import ad_bed_15_upbeat from "../content/entries/ad-bed-15-upbeat.json";
import ad_bed_30_lifestyle from "../content/entries/ad-bed-30-lifestyle.json";
import ad_bed_6_bumper from "../content/entries/ad-bed-6-bumper.json";
import ad_bed_60_story from "../content/entries/ad-bed-60-story.json";
import ambient_bed_lofi from "../content/entries/ambient-bed-lofi.json";
import chaos_calm_01 from "../content/entries/chaos-calm-01.json";
import chaos_calm_02 from "../content/entries/chaos-calm-02.json";
import chaos_calm_03 from "../content/entries/chaos-calm-03.json";
import chaos_calm_04 from "../content/entries/chaos-calm-04.json";
import chaos_calm_05 from "../content/entries/chaos-calm-05.json";
import drop_impact_heavy from "../content/entries/drop-impact-heavy.json";
import drop_whoosh_stinger from "../content/entries/drop-whoosh-stinger.json";
import logo_sting_bright from "../content/entries/logo-sting-bright.json";
import riser_tension_8s from "../content/entries/riser-tension-8s.json";
import ui_error_soft from "../content/entries/ui-error-soft.json";
import ui_success_chime from "../content/entries/ui-success-chime.json";

import type { SoundEntry } from "./entries-types";

export const ALL_ENTRIES: SoundEntry[] = [ad_bed_15_upbeat, ad_bed_30_lifestyle, ad_bed_6_bumper, ad_bed_60_story, ambient_bed_lofi, chaos_calm_01, chaos_calm_02, chaos_calm_03, chaos_calm_04, chaos_calm_05, drop_impact_heavy, drop_whoosh_stinger, logo_sting_bright, riser_tension_8s, ui_error_soft, ui_success_chime];
