/** Generated by scripts/sync-hero8-take-assets.mjs — do not edit by hand. */
import type { Hero8CodexTakeRow } from "./hero8-takes-types";

export const HERO8_CODEX_TAKE_ROWS: Hero8CodexTakeRow[] = [
  {
    "entryId": "heavy-boom-meme",
    "takeId": "codex-1",
    "codexTake": 1,
    "lufs": -14,
    "truePeakDbTp": -2.379,
    "durationSec": 1.5,
    "mp3": "/assets/heavy-boom-meme/takes/codex-1.mp3",
    "wav": "/assets/heavy-boom-meme/takes/codex-1.wav"
  },
  {
    "entryId": "heavy-boom-meme",
    "takeId": "codex-2",
    "codexTake": 2,
    "lufs": -14,
    "truePeakDbTp": -2.212,
    "durationSec": 1.5,
    "mp3": "/assets/heavy-boom-meme/takes/codex-2.mp3",
    "wav": "/assets/heavy-boom-meme/takes/codex-2.wav"
  },
  {
    "entryId": "heavy-boom-meme",
    "takeId": "codex-3",
    "codexTake": 3,
    "lufs": -14,
    "truePeakDbTp": -1.525,
    "durationSec": 1.5,
    "mp3": "/assets/heavy-boom-meme/takes/codex-3.mp3",
    "wav": "/assets/heavy-boom-meme/takes/codex-3.wav"
  },
  {
    "entryId": "whoosh-pass-by",
    "takeId": "codex-1",
    "codexTake": 1,
    "lufs": -14,
    "truePeakDbTp": -2.632,
    "durationSec": 1.2,
    "mp3": "/assets/whoosh-pass-by/takes/codex-1.mp3",
    "wav": "/assets/whoosh-pass-by/takes/codex-1.wav"
  },
  {
    "entryId": "whoosh-pass-by",
    "takeId": "codex-2",
    "codexTake": 2,
    "lufs": -14,
    "truePeakDbTp": -2.172,
    "durationSec": 1.2,
    "mp3": "/assets/whoosh-pass-by/takes/codex-2.mp3",
    "wav": "/assets/whoosh-pass-by/takes/codex-2.wav"
  },
  {
    "entryId": "whoosh-pass-by",
    "takeId": "codex-3",
    "codexTake": 3,
    "lufs": -14,
    "truePeakDbTp": -3.209,
    "durationSec": 1.2,
    "mp3": "/assets/whoosh-pass-by/takes/codex-3.mp3",
    "wav": "/assets/whoosh-pass-by/takes/codex-3.wav"
  },
  {
    "entryId": "ui-cozy-sprite",
    "takeId": "codex-1",
    "codexTake": 1,
    "lufs": -17,
    "truePeakDbTp": -2.079,
    "durationSec": 4,
    "mp3": "/assets/ui-cozy-sprite/takes/codex-1.mp3",
    "wav": "/assets/ui-cozy-sprite/takes/codex-1.wav"
  },
  {
    "entryId": "ui-cozy-sprite",
    "takeId": "codex-2",
    "codexTake": 2,
    "lufs": -17,
    "truePeakDbTp": -1.607,
    "durationSec": 4,
    "mp3": "/assets/ui-cozy-sprite/takes/codex-2.mp3",
    "wav": "/assets/ui-cozy-sprite/takes/codex-2.wav"
  },
  {
    "entryId": "ui-cozy-sprite",
    "takeId": "codex-3",
    "codexTake": 3,
    "lufs": -17,
    "truePeakDbTp": -2.641,
    "durationSec": 4,
    "mp3": "/assets/ui-cozy-sprite/takes/codex-3.mp3",
    "wav": "/assets/ui-cozy-sprite/takes/codex-3.wav"
  },
  {
    "entryId": "endless-riser-shepard",
    "takeId": "codex-1",
    "codexTake": 1,
    "lufs": -14,
    "truePeakDbTp": -5.693,
    "durationSec": 12,
    "mp3": "/assets/endless-riser-shepard/takes/codex-1.mp3",
    "wav": "/assets/endless-riser-shepard/takes/codex-1.wav"
  },
  {
    "entryId": "endless-riser-shepard",
    "takeId": "codex-2",
    "codexTake": 2,
    "lufs": -14,
    "truePeakDbTp": -6.371,
    "durationSec": 12,
    "mp3": "/assets/endless-riser-shepard/takes/codex-2.mp3",
    "wav": "/assets/endless-riser-shepard/takes/codex-2.wav"
  },
  {
    "entryId": "endless-riser-shepard",
    "takeId": "codex-3",
    "codexTake": 3,
    "lufs": -14,
    "truePeakDbTp": -5.589,
    "durationSec": 12,
    "mp3": "/assets/endless-riser-shepard/takes/codex-3.mp3",
    "wav": "/assets/endless-riser-shepard/takes/codex-3.wav"
  },
  {
    "entryId": "dialup-modem-56k",
    "takeId": "codex-1",
    "codexTake": 1,
    "lufs": -14,
    "truePeakDbTp": -1.475,
    "durationSec": 12,
    "mp3": "/assets/dialup-modem-56k/takes/codex-1.mp3",
    "wav": "/assets/dialup-modem-56k/takes/codex-1.wav"
  },
  {
    "entryId": "dialup-modem-56k",
    "takeId": "codex-2",
    "codexTake": 2,
    "lufs": -14,
    "truePeakDbTp": -5.823,
    "durationSec": 12,
    "mp3": "/assets/dialup-modem-56k/takes/codex-2.mp3",
    "wav": "/assets/dialup-modem-56k/takes/codex-2.wav"
  },
  {
    "entryId": "dialup-modem-56k",
    "takeId": "codex-3",
    "codexTake": 3,
    "lufs": -14,
    "truePeakDbTp": -4.05,
    "durationSec": 12,
    "mp3": "/assets/dialup-modem-56k/takes/codex-3.mp3",
    "wav": "/assets/dialup-modem-56k/takes/codex-3.wav"
  },
  {
    "entryId": "wah-wah-fail",
    "takeId": "codex-1",
    "codexTake": 1,
    "lufs": -14,
    "truePeakDbTp": -5.047,
    "durationSec": 2.8,
    "mp3": "/assets/wah-wah-fail/takes/codex-1.mp3",
    "wav": "/assets/wah-wah-fail/takes/codex-1.wav"
  },
  {
    "entryId": "wah-wah-fail",
    "takeId": "codex-2",
    "codexTake": 2,
    "lufs": -14,
    "truePeakDbTp": -3.064,
    "durationSec": 2.8,
    "mp3": "/assets/wah-wah-fail/takes/codex-2.mp3",
    "wav": "/assets/wah-wah-fail/takes/codex-2.wav"
  },
  {
    "entryId": "wah-wah-fail",
    "takeId": "codex-3",
    "codexTake": 3,
    "lufs": -14,
    "truePeakDbTp": -5.279,
    "durationSec": 2.8,
    "mp3": "/assets/wah-wah-fail/takes/codex-3.mp3",
    "wav": "/assets/wah-wah-fail/takes/codex-3.wav"
  },
  {
    "entryId": "arcade-game-over",
    "takeId": "codex-1",
    "codexTake": 1,
    "lufs": -14,
    "truePeakDbTp": -2.032,
    "durationSec": 1.8,
    "mp3": "/assets/arcade-game-over/takes/codex-1.mp3",
    "wav": "/assets/arcade-game-over/takes/codex-1.wav"
  },
  {
    "entryId": "arcade-game-over",
    "takeId": "codex-2",
    "codexTake": 2,
    "lufs": -14,
    "truePeakDbTp": -3.211,
    "durationSec": 1.8,
    "mp3": "/assets/arcade-game-over/takes/codex-2.mp3",
    "wav": "/assets/arcade-game-over/takes/codex-2.wav"
  },
  {
    "entryId": "arcade-game-over",
    "takeId": "codex-3",
    "codexTake": 3,
    "lufs": -14,
    "truePeakDbTp": -2.578,
    "durationSec": 1.8,
    "mp3": "/assets/arcade-game-over/takes/codex-3.mp3",
    "wav": "/assets/arcade-game-over/takes/codex-3.wav"
  },
  {
    "entryId": "trailer-braam-hit",
    "takeId": "codex-1",
    "codexTake": 1,
    "lufs": -14,
    "truePeakDbTp": -2.338,
    "durationSec": 4,
    "mp3": "/assets/trailer-braam-hit/takes/codex-1.mp3",
    "wav": "/assets/trailer-braam-hit/takes/codex-1.wav"
  },
  {
    "entryId": "trailer-braam-hit",
    "takeId": "codex-2",
    "codexTake": 2,
    "lufs": -14,
    "truePeakDbTp": -1.293,
    "durationSec": 4,
    "mp3": "/assets/trailer-braam-hit/takes/codex-2.mp3",
    "wav": "/assets/trailer-braam-hit/takes/codex-2.wav"
  },
  {
    "entryId": "trailer-braam-hit",
    "takeId": "codex-3",
    "codexTake": 3,
    "lufs": -14,
    "truePeakDbTp": -1.957,
    "durationSec": 4,
    "mp3": "/assets/trailer-braam-hit/takes/codex-3.mp3",
    "wav": "/assets/trailer-braam-hit/takes/codex-3.wav"
  },
  {
    "entryId": "game-coin-pickup",
    "takeId": "codex-1",
    "codexTake": 1,
    "lufs": -17,
    "truePeakDbTp": -4.802,
    "durationSec": 0.5,
    "mp3": "/assets/game-coin-pickup/takes/codex-1.mp3",
    "wav": "/assets/game-coin-pickup/takes/codex-1.wav"
  },
  {
    "entryId": "game-coin-pickup",
    "takeId": "codex-2",
    "codexTake": 2,
    "lufs": -17,
    "truePeakDbTp": -2.686,
    "durationSec": 0.5,
    "mp3": "/assets/game-coin-pickup/takes/codex-2.mp3",
    "wav": "/assets/game-coin-pickup/takes/codex-2.wav"
  },
  {
    "entryId": "game-coin-pickup",
    "takeId": "codex-3",
    "codexTake": 3,
    "lufs": -17,
    "truePeakDbTp": -5.878,
    "durationSec": 0.5,
    "mp3": "/assets/game-coin-pickup/takes/codex-3.mp3",
    "wav": "/assets/game-coin-pickup/takes/codex-3.wav"
  }
];
