import type { SoundEntry } from "@/lib/entries-types";
import {
  CODEX_MODEL_ID,
  COMMUNITY_MODEL_ID,
  LOCAL_SYNTH_MODEL_ID,
  isOpusApiModelId,
} from "@/lib/model-display";

export type BadgeVariant = "local" | "opus" | "community" | "codex";

export function modelBadgeDisplay(
  entry: Pick<SoundEntry, "modelId">,
): { label: string; tooltip: string; variant: BadgeVariant } {
  if (entry.modelId === COMMUNITY_MODEL_ID) {
    return {
      label: "Community",
      tooltip: "Submitted and published via community review",
      variant: "community",
    };
  }
  if (entry.modelId === LOCAL_SYNTH_MODEL_ID) {
    return {
      label: "Local synth",
      tooltip: "Synthesised locally from the prompt; not generated by Opus",
      variant: "local",
    };
  }
  if (entry.modelId === CODEX_MODEL_ID) {
    return {
      label: "Codex",
      tooltip: "OpenAI Codex-authored local synthesis; not Claude Opus",
      variant: "codex",
    };
  }
  if (isOpusApiModelId(entry.modelId)) {
    const label =
      entry.modelId === "claude-opus-5-5" ? "Claude Opus 5.5" : "Claude Opus";
    return {
      label,
      tooltip: "Generated by Anthropic Opus via the Messages API",
      variant: "opus",
    };
  }
  return {
    label: entry.modelId,
    tooltip: entry.modelId,
    variant: "opus",
  };
}
