import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const dir = path.join(root, "content", "entries");
const files = fs.readdirSync(dir).filter((f) => f.endsWith(".json")).sort();

const imports = files
  .map((f) => {
    const id = f.replace(/\.json$/, "").replace(/[^a-zA-Z0-9]/g, "_");
    return `import ${id} from "../content/entries/${f}";`;
  })
  .join("\n");

const ids = files.map((f) => f.replace(/\.json$/, "").replace(/[^a-zA-Z0-9]/g, "_"));

const out = `/* Auto-generated by scripts/sync-entries.mjs — do not edit */\n${imports}\n\nimport type { SoundEntry } from "./entries-types";\n\nexport const ALL_ENTRIES: SoundEntry[] = [${ids.join(", ")}];\n`;

fs.writeFileSync(path.join(root, "lib", "entries.generated.ts"), out);
console.log(`Synced ${files.length} entries → lib/entries.generated.ts`);
