import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";

const root = path.resolve(import.meta.dirname, "..");
const dir = path.join(root, "content", "blog");

if (!fs.existsSync(dir)) {
  fs.mkdirSync(dir, { recursive: true });
}

const files = fs.existsSync(dir)
  ? fs.readdirSync(dir).filter((f) => f.endsWith(".md")).sort()
  : [];

function escapeForTs(str) {
  return JSON.stringify(str);
}

const posts = files.map((f) => {
  const raw = fs.readFileSync(path.join(dir, f), "utf8");
  const { data, content } = matter(raw);
  const slug = String(data.slug ?? f.replace(/\.md$/, ""));
  return {
    title: String(data.title ?? slug),
    slug,
    description: String(data.description ?? ""),
    date: String(data.date ?? ""),
    keywords: Array.isArray(data.keywords) ? data.keywords.map(String) : [],
    faq: Array.isArray(data.faq)
      ? data.faq.map((item) => ({
          q: String(item?.q ?? item?.question ?? ""),
          a: String(item?.a ?? item?.answer ?? ""),
        }))
      : [],
    draft: Boolean(data.draft),
    body: content.trim(),
  };
});

const out = `/* Auto-generated by scripts/sync-blog.mjs — do not edit */
import type { BlogPost } from "./blog-types";

export const ALL_BLOG_POSTS: BlogPost[] = ${JSON.stringify(posts, null, 2)} as BlogPost[];
`;

fs.writeFileSync(path.join(root, "lib", "blog.generated.ts"), out);
console.log(`Synced ${files.length} blog post(s) → lib/blog.generated.ts`);
