"""Generated by claude-opus-5-5 (Anthropic Messages API) on 2026-10-06 for Opus Sound Directory entry `ui-success-chime`. Seed 42; candidate 1/3, fix round 0. Runs with numpy/scipy only: `python generate.py [OUT_PATH]`.


Make a 0.5 s UI success sound effect for video at 30 fps.
Output: one WAV, 48 kHz / 16-bit / stereo, exactly 24000 samples.
Python + numpy/scipy only. Synthesise everything (no samples, no downloads). Fixed random seed.
Sound: two-tone pleasant chime, fast decay, no harsh highs; centre at frame 0.
Master: -14 LUFS integrated, true peak <= -1 dBTP.
Verify length, loudness, peak with ffmpeg ebur128; render spectrogram; fix until checks pass.
"""
# Design notes (Candidate A, "ui-success-chime"):
#   Use case : confirmation "ding-ding" for app UI / on-screen checkmark in video edits.
#   Shape    : hit on sample 0 (C6) -> rising major third (E6) at 75 ms -> smooth decay to silence.
#   Spectrum : 0.5-4 kHz focus, gentle 7 kHz low-pass, nothing below ~30 Hz, no hiss.
#   Timbre   : sine fundamentals + soft sub-octave body + faint bell partial + tiny
#              band-passed mallet tick for definition (very low level, not clicky).
#   Stereo   : near-centre; tone 1 nudged left, tone 2 nudged right, slight L/R detune.

import sys
import os
import wave

import numpy as np
from scipy.signal import lfilter, butter, sosfilt, resample_poly
from scipy.ndimage import minimum_filter1d

SAMPLE_RATE = 48000
SEED = 42
DURATION_SEC = 0.5
N_SAMPLES = 24000
BPM = 120
FPS = 30
KEY = "C major"
TARGET_LUFS = -14.0
TP_CEILING_DB = -1.5      # internal ceiling (spec: <= -1 dBTP)

rng = np.random.default_rng(SEED)
t = np.arange(N_SAMPLES) / SAMPLE_RATE


# ----------------------------------------------------------------------------- synthesis
def pan_gains(p):
    """Equal-power pan, p in [-1, 1]."""
    a = (p + 1.0) * np.pi / 4.0
    return np.cos(a), np.sin(a)


def chime_voice(f0, t0, amp, tau, pan, detune=0.0012):
    """One chime strike starting at t0 seconds. Returns (N, 2)."""
    out = np.zeros((N_SAMPLES, 2))
    tl = t - t0
    m = tl >= 0
    tl = np.where(m, tl, 0.0)
    attack = 1.0 - np.exp(-tl / 0.0010)          # ~3 ms to full, starts at exactly 0
    # (ratio, rel amp, tau multiplier, phase)
    partials = [
        (1.0, 1.00, 1.00, 0.0),     # fundamental
        (0.5, 0.14, 1.30, 0.0),     # soft sub-octave body (warmth)
        (2.0, 0.16, 0.45, 0.3),     # octave shimmer
        (3.0, 0.035, 0.25, 0.7),    # gentle 12th
        (2.76, 0.045, 0.12, 1.1),   # brief bell-like inharmonic "ting"
    ]
    lg, rg = pan_gains(pan)
    for ch, (g, dt) in enumerate(((lg, -detune), (rg, detune))):
        sig = np.zeros(N_SAMPLES)
        for ratio, ra, tm, ph in partials:
            f = f0 * ratio * (1.0 + dt)
            env = attack * np.exp(-tl / (tau * tm))
            sig += ra * env * np.sin(2 * np.pi * f * tl + ph)
        out[:, ch] = amp * g * sig * m
    return out


def mallet_tick(t0, amp):
    """Very short band-passed noise tick for transient definition."""
    out = np.zeros((N_SAMPLES, 2))
    n = int(0.006 * SAMPLE_RATE)
    s0 = int(round(t0 * SAMPLE_RATE))
    noise = rng.standard_normal((n, 2))
    sos = butter(2, [1800, 4500], btype="bandpass", fs=SAMPLE_RATE, output="sos")
    noise = sosfilt(sos, noise, axis=0)
    tt = np.arange(n) / SAMPLE_RATE
    env = (1 - np.exp(-tt / 0.0004)) * np.exp(-tt / 0.0012)
    noise *= env[:, None]
    noise /= np.max(np.abs(noise)) + 1e-12
    end = min(N_SAMPLES, s0 + n)
    out[s0:end] = amp * noise[: end - s0]
    return out


def synthesize():
    x = np.zeros((N_SAMPLES, 2))
    # Tone 1: C6 on sample 0 (frame 0 cue)
    x += chime_voice(1046.50, 0.0, 1.00, 0.095, pan=-0.18)
    # Tone 2: E6, rising major third, 75 ms later, longer ring
    x += chime_voice(1318.51, 0.075, 0.92, 0.135, pan=+0.18)
    # Transient ticks (subtle)
    x += mallet_tick(0.0, 0.07)
    x += mallet_tick(0.075, 0.055)

    # Tone shaping: no harsh highs, no DC / rumble
    lp = butter(4, 7000, btype="lowpass", fs=SAMPLE_RATE, output="sos")
    hp = butter(2, 30, btype="highpass", fs=SAMPLE_RATE, output="sos")
    x = sosfilt(lp, x, axis=0)
    x = sosfilt(hp, x, axis=0)

    # Smooth tail fade to true silence (last 60 ms)
    nf = int(0.060 * SAMPLE_RATE)
    fade = 0.5 * (1 + np.cos(np.linspace(0, np.pi, nf)))
    x[-nf:] *= fade[:, None]
    x[0] = 0.0
    x -= 0.0  # DC handled by HPF; signal starts at zero
    x /= np.max(np.abs(x)) + 1e-12
    return x * 0.5


# ----------------------------------------------------------------------------- metering
K1_B = [1.53512485958697, -2.69169618940638, 1.19839281085285]
K1_A = [1.0, -1.69065929318241, 0.73248077421585]
K2_B = [1.0, -2.0, 1.0]
K2_A = [1.0, -1.99004745483398, 0.99007225036621]


def integrated_lufs(x):
    y = lfilter(K1_B, K1_A, x, axis=0)
    y = lfilter(K2_B, K2_A, y, axis=0)
    blk = int(0.4 * SAMPLE_RATE)
    hop = int(0.1 * SAMPLE_RATE)
    n = y.shape[0]
    if n < blk:
        return -120.0
    starts = np.arange(0, n - blk + 1, hop)
    sq = y ** 2
    cs = np.vstack([np.zeros((1, 2)), np.cumsum(sq, axis=0)])
    z = (cs[starts + blk] - cs[starts]) / blk           # (blocks, ch)
    zsum = z.sum(axis=1)
    lk = -0.691 + 10 * np.log10(zsum + 1e-20)
    g1 = lk > -70.0
    if not np.any(g1):
        return -120.0
    rel = -0.691 + 10 * np.log10(np.mean(zsum[g1])) - 10.0
    g2 = g1 & (lk > rel)
    if not np.any(g2):
        return -120.0
    return -0.691 + 10 * np.log10(np.mean(zsum[g2]))


def oversampled_peak_per_sample(x):
    up = resample_poly(x, 4, 1, axis=0)
    up = np.abs(up).max(axis=1)
    up = up[: 4 * x.shape[0]].reshape(-1, 4).max(axis=1)
    return up


def true_peak_db(x):
    return 20 * np.log10(np.max(oversampled_peak_per_sample(x)) + 1e-20)


def limiter(x, ceiling_db, look_ms=1.5):
    ceil = 10 ** (ceiling_db / 20)
    pk = oversampled_peak_per_sample(x)
    need = np.minimum(1.0, ceil / (pk + 1e-12))
    if np.all(need >= 1.0):
        return x
    L = max(1, int(look_ms * 1e-3 * SAMPLE_RATE))
    g = minimum_filter1d(need, size=2 * L + 1, mode="nearest")
    box = np.ones(L + 1) / (L + 1)
    g = np.convolve(np.pad(g, (L, L), mode="edge"), box, mode="same")[L:-L]
    g = np.minimum(g, 1.0)
    return x * g[:, None]


def master(raw):
    gain = 1.0
    y = raw
    for _ in range(12):
        y = limiter(raw * gain, TP_CEILING_DB)
        lufs = integrated_lufs(y)
        if abs(lufs - TARGET_LUFS) < 0.05:
            break
        gain *= 10 ** ((TARGET_LUFS - lufs) / 20)
    # final safety on true peak
    for _ in range(4):
        tp = true_peak_db(y)
        if tp <= TP_CEILING_DB + 0.05:
            break
        y = limiter(y, TP_CEILING_DB - 0.2)
    return y


def quantise(y):
    d = (rng.random(y.shape) - rng.random(y.shape))      # TPDF, +/-1 LSB
    q = np.round(y * 32767.0 + d * 0.5)
    q = np.clip(q, -32767, 32767).astype("<i2")
    return q


def main():
    out_path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "out.wav")
    raw = synthesize().astype(np.float64)
    y = master(raw)
    y = np.nan_to_num(y, nan=0.0, posinf=0.0, neginf=0.0)
    y = np.clip(y, -0.999, 0.999).astype(np.float32)
    q = quantise(y.astype(np.float64))
    assert q.shape == (N_SAMPLES, 2)
    with wave.open(out_path, "wb") as w:
        w.setnchannels(2)
        w.setsampwidth(2)
        w.setframerate(SAMPLE_RATE)
        w.writeframes(q.tobytes())


if __name__ == "__main__":
    main()
