#!/usr/bin/env python3
"""
Opus Sound Directory runner.

Mock mode (default): synthesise placeholder WAV, spectrogram, metrics.
Future: wire Claude Agent SDK or `claude -p` via --agent flag (interface only in MVP).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(Path(__file__).resolve().parent))

from mock_generate import synthesise, write_code_stub, write_wav
from verify import render_spectrogram, verify_wav

SAMPLE_RATE = 48000


def load_entry(entry_path: Path) -> dict:
    return json.loads(entry_path.read_text(encoding="utf-8"))


def save_entry(entry_path: Path, data: dict) -> None:
    entry_path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def run_entry(
    entry_path: Path,
    mock: bool = True,
    best_of: int = 1,
) -> dict:
    entry = load_entry(entry_path)
    entry_id = entry["id"]
    timing = entry.get("timing", {})
    duration = float(timing.get("durationSec", 3))
    expected_samples = timing.get("samples")
    seed = int(entry.get("seed", 42))
    category = entry.get("category", "ambient")

    asset_dir = ROOT / "public" / "assets" / entry_id
    wav_path = asset_dir / "out.wav"
    spec_path = asset_dir / "spectrogram.png"
    code_path = asset_dir / "generate.py"

    best_metrics = None
    best_seed = seed

    for attempt in range(best_of):
        attempt_seed = seed + attempt
        if mock:
            audio = synthesise(category, duration, attempt_seed)
            write_wav(wav_path, audio)
            write_code_stub(code_path, entry_id, entry.get("prompt", ""), attempt_seed)
        else:
            raise NotImplementedError(
                "Agent mode not configured. Set ANTHROPIC_API_KEY and implement agent_generate(). "
                "See README for `claude -p` integration notes."
            )

        metrics = verify_wav(wav_path, expected_samples=expected_samples)
        render_spectrogram(wav_path, spec_path)

        if best_metrics is None or (metrics.get("lufs") or -70) > (best_metrics.get("lufs") or -70):
            best_metrics = metrics
            best_seed = attempt_seed

    entry["seed"] = best_seed
    entry["metrics"] = {
        "lufs": best_metrics["lufs"],
        "truePeak": best_metrics["truePeak"],
        "durationSec": best_metrics["durationSec"],
        "passedChecks": best_metrics["passedChecks"],
    }
    entry["assets"] = {
        "wav": f"/assets/{entry_id}/out.wav",
        "mp3": f"/assets/{entry_id}/out.mp3",
        "spectrogram": f"/assets/{entry_id}/spectrogram.png",
        "code": f"/assets/{entry_id}/generate.py",
    }
    entry["notes"] = "Generated by runner (mock mode)." if mock else entry.get("notes", "")
    save_entry(entry_path, entry)

    # Optional MP3
    mp3_path = asset_dir / "out.mp3"
    try:
        import shutil
        import subprocess

        if shutil.which("ffmpeg"):
            subprocess.run(
                ["ffmpeg", "-y", "-i", str(wav_path), "-q:a", "4", str(mp3_path)],
                check=True,
                capture_output=True,
            )
    except Exception:
        pass

    return entry


def main() -> None:
    parser = argparse.ArgumentParser(description="Run Opus Sound Directory generation")
    parser.add_argument("entry", type=Path, help="Path to content/entries/<id>.json")
    parser.add_argument("--mock", action="store_true", default=True, help="Mock synthesis (default)")
    parser.add_argument("--agent", action="store_true", help="Use Claude agent (not implemented)")
    parser.add_argument("--best-of", type=int, default=1, help="Run N times, keep best LUFS")
    args = parser.parse_args()

    mock = not args.agent
    result = run_entry(args.entry.resolve(), mock=mock, best_of=args.best_of)
    print(json.dumps(result["metrics"], indent=2))


if __name__ == "__main__":
    main()
